

services:
  app:
    build: .
    container_name: app_fotos_pdf_server
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=postgres
      - BUCKET_ENDPOINT=http://minio:9000
    depends_on:
      - postgres
      - minio

  postgres:
    image: postgres:15-alpine
    container_name: app_database
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: senha_secreta_123
      POSTGRES_DB: app_fotos_pdf
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Bucket de Mídias MinIO corrigido
  minio:
    image: minio/minio
    container_name: app_bucket
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin_bucket
      MINIO_ROOT_PASSWORD: senha_bucket_123
    volumes:
      # 1. Apontamos o volume para a raiz /data do container
      - "C:/Users/flixz/pdfs:/data"
    # 2. Usamos o comando 'mkdir' antes do servidor iniciar para garantir que a pasta do bucket exista no Windows
    entrypoint: >
      sh -c "mkdir -p /data/midias-pdf && minio server /data --console-address ':9001'"

volumes:
  postgres_data: